language: node_js
node_js:
- '4.1'
script: make publish
before_script:
- git config --global user.email "build@dan.cx"
- git config --global user.name "DanBuild"
env:
  global:
    secure: bsfs43r8MQ9anX8J5tq4K2whshu/cHrYTeUaJCXvq84RAWhLgNeCi3BMvGNrMzdw59V+h38PkutqlpTTgR/S4UCdCqDDd0KJONCbbndJCrRygfYBi+qTdaKphzeT6mMBUS69FtrKsHyCUNfKFCHriXF7ODUvpy/qeVWOC8h5vsk=
