language: ruby

rvm:
  - 2.2.5

before_install:
  - nvm install node
  - npm install

script:
  - ./scripts/download-readmes.js
  - npm test && npm run lint && bundle exec rake

git:
  submodules: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
