# Site settings
title: Babel
tagline: The transpiler for writing next generation JavaScript
description: The transpiler for writing next generation JavaScript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://babeljs.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: babel
exclude: ["node_modules"]

# Build settings
markdown: redcarpet
# markdown: kramdown
highlighter: pygments

redcarpet:
  extensions: ['tables', 'no_intra_emphasis', 'autolink', 'with_toc_data']

# kramdown:
#   input: GFM
#   hard_wrap: false

# header navigation
navigation:
- title: Learn ES6
  url: /docs/learn-es6/
- title: Using Babel
  url: /docs/using-babel/
- title: Docs
  url: /docs/usage/
  subnav:
  - title: CLI
    url: /docs/usage/cli/
  - title: Require Hook
    url: /docs/usage/require/
  - title: API
    url: /docs/usage/api/
  - title: Options
    url: /docs/usage/options/
  - title: Runtime
    url: /docs/usage/runtime/
  - title: Caveats
    url: /docs/usage/caveats/
  - title: Modules
    url: /docs/usage/modules/
  - title: Polyfill
    url: /docs/usage/polyfill/
  - title: Transformers
    url: /docs/usage/transformers/
  - title: Loose mode
    url: /docs/usage/loose/
  - title: Browser
    url: /docs/usage/browser/
  - title: Experimental
    url: /docs/usage/experimental/
  - title: Playground
    url: /docs/usage/playground/
  - title: JSX
    url: /docs/usage/jsx/
  - title: External helpers
    url: /docs/usage/external-helpers/
- title: Compare
  url: /docs/compare/
- title: Try it out
  url: /repl/
- title: FAQ
  url: /docs/faq/

# Blog Settings
permalink: /blog/:year/:month/:day/:title
paginate: 1

gems:
  - jekyll-redirect-from
