# Site settings
title: 6to5
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/6to5.github.io" # the subpath of your site, e.g. /blog/
url: "https://6to5.org" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  6to5

# Build settings
markdown: redcarpet
# markdown: kramdown
highlighter: pygments

redcarpet:
  extensions: ['tables', 'no_intra_emphasis', 'autolink', 'with_toc_data']

# kramdown:
#   input: GFM
#   hard_wrap: false

# header navigation
navigation:
- title: Tour
  url: /docs/tour/
- title: Setup
  url: /docs/setup/
- title: Usage
  url: /docs/usage/
- title: Compare
  url: /docs/compare/
- title: Caveats
  url: /docs/caveats/
- title: REPL
  url: /repl/

# Blog Settings
permalink: /blog/:year/:month/:day/:title
paginate: 1

gems:
  - jekyll-redirect-from
